### PR TITLE
Upgraded to elastic.v5

### PR DESCRIPTION
**Pull request by mnbbrown**
Firstly, thanks for a very good little tool @knes1!

I was doing some internal testing with elktail and migrated it to using elasticsearch v5.x. 
Thought some of my changes my be useful.

Given the breaking changes introduced in v5.x I'm not sure how backwards compatible it is. 

Apologies for the messy pull request.

### CODE REVIEW

**Comment by knes1** [comment]
Hi! Sorry for a late response!
PR looks good. I'm working on CI/testing setup so that changes on elktail can be tested VS different versions of elastic. As soon as I'm done with that, I'm merging your PR.
Thank you for contributing!

**Comment by thomaspeitz** [comment]
@knes1 Any update on that? Love your tool :) Just tested with elasticsearch v5 and the pull request works. Would love to see it merged and released.

**Comment by knes1** [comment]
I'll be working on it over the weekend. Basically, I'd love to have one elktail version that supports all elastic versions which is tricky. I'll give it a try this weekend. If I don't manage to make it support all versions in a single app, I'll just create several builds of elktail for specific elastic versions.

**Comment by thomaspeitz** [comment]
Either way i appreciate your fast feedback and look forward to use your tool :)

**Comment by gajus** [comment]
@knes1 any chance of this getting out?

**Comment by conner** [comment]
thanks @mnbbrown been using this and works a treat

**Comment by xamox** [comment]
Thanks for adding this, just upgraded ES to v5 and was sad to see elktail not working.

**Comment by jbrownsc** [comment]
Any hope getting this merged?

**Pull request merged**
