### PR TITLE
Merge all sorts of other people's contributions

### PR DESCRIPTION
**Pull request by SvenDowideit**
@knes1 I wanted to try elktail out, and wanted to see where things stood, so merge together all the things I came across.

I'm going to make an auto-building Docker image from this - but love to know if you're thinking to continue working on this, or if I should just keep a fork

### CODE REVIEW

**Comment by SvenDowideit** [comment]
this includes changes from 

* @bonovoxly	https://github.com/bonovoxly/elktail (fetch)
* @conner	https://github.com/conner/elktail (fetch)
* @gabe-sorensen	https://github.com/gabe-sorensen/elktail (fetch)
* @mnbbrown	https://github.com/mnbbrown/elktail (fetch)
* @portante	https://github.com/portante/elktail (fetch)
* @quipper	https://github.com/quipper/elktail (fetch)
* @rindek	https://github.com/rindek/elktail (fetch)
* @rvanider	https://github.com/rvanider/elktail (fetch)

**Comment by dualbus** [comment]
@SvenDowideit are you maintaining a fork for elktail? (since this seems abandoned)

**Comment by SvenDowideit** [comment]
@dualbus I was honestly hoping not to
but I may have to work out something :/

**Comment by alphacc** [comment]
@SvenDowideit If you want to share the burden of forking and maintaining let me know, happy to help if I am not alone ;-)

**Comment by SvenDowideit** [comment]
to be honest, I'm hoping to move away from using elasticsearch - i feel it uses alot more resources than is justified for how we're using it.
but on the other hand, we havn't looked at anything other than loki atm, and that's too early in its dev cycle for our use :)

**Comment by SvenDowideit** [comment]
we've moved to using loki, its a much simpler model for our uses

**Comment by stappersg** [comment]
Link to [Loki,  Prometheus-inspired logging for cloud natives](https://grafana.com/oss/loki#about)

**Pull request closed without merging**
